Add missing expectation before checking metadata
We weren't checking whether the request creating the proposal had
finished before checking the document. That's probably why this test has
recently failed on our CI:

```
1) Documents Metadata download document without metadata
     Failure/Error: io = URI.parse(
                          "#{app_host}#{polymorphic_path(
                                        Document.last.attachment)}"
                        ).open

     NoMethodError:
       undefined method `attachment' for nil:NilClass
```